version: "3.8"

services:
  app:
    build: .
    depends_on:
      - redis
    networks:
      - barberbot_app-network
    restart: unless-stopped

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - barberbot_app-network

volumes:
  redis-data:

networks:
  barberbot_app-network:
    driver: bridge
