# Общие сообщения
welcome_message: |
  ✂️ Привет, {{.Username}}! Я - бот барбера Олеси, и моя задача сделать твой визит максимально удобным.
  Я работаю по выходным, и ты всегда можешь найти меня по адресу: улица Куйбышева, 79.
  
  Вот что ты можешь сделать:
  - 🕒 /book - Забронировать время для стрижки или другой услуги
  - 👩‍🎨 /services - Узнать о всех услугах и их стоимости
  - 🤙 /contact - Связаться с Олесей напрямую
  - 💇 /about - Узнать больше об Олесе и ее опыте работы
  - 🔄 /reschedule - Изменить существующую запись
  - ❌ /cancel - Отменить запись
  - 📋 /my_appointments - Посмотреть свои записи

  Если тебе нужна помощь, просто напиши /help.

unknown_command: |
  ❓ Хмм, кажется, я не знаю такой команды. Попробуй ещё раз или напиши /help, чтобы узнать, что я умею!

# Сообщения о услугах
services_list: |
  🛠️ Услуги и цены:
  1. Мужская стрижка – 1100 ₽ (60 минут)
  2. Борода – 700 ₽ (30 минут)
  3. Детская стрижка – 1000 ₽ (60 минут)
  4. Воск – 300 ₽ (15 минут)
  5. Тонировка бороды – 900 ₽ (30 минут)
  6. Тонировка седины – 1000 ₽ (30 минут)

  Выбирай и записывайся через /book!

help_message: |
  ❓ Нужна помощь? Вот список доступных команд:
  - /book – запись на услугу
  - /cancel – отмена записи
  - /reschedule – перенос записи
  - /services – услуги и цены
  - /my_appointments – твои записи
  - /contact – связь с Олесей
  - /about - узнать больше об Олесе и ее опыте работы

# Контактная информация
contact_info: |
  📞 Если у тебя возникли вопросы, можешь позвонить по номеру +7 982 467 1365 или написать Олесе в Telegram: t.me/OlesyaHudanina

# Информация о мастере
about_master: |
  👩‍🎨 Знакомься с Олеся! 

  Олеся — профессиональный барбер с опытом 1,5 года. Её стиль — это сочетание классических техник и современных трендов. 

  🌟 Квалификация:
  - Сертифицированный мастер по стрижке и укладке волос
  ✂️ Услуги, которые предлагает Олеся:
  - Мужские стрижки
  - Уход за бородой и усами
  - Укладка волос
  - Консультации по выбору стиля

  🌍 Где найти Олесю:
  Она принимает клиентов по адресу: Улица Куйбышева, 79, в уютном салоне

  📅 Если ты готов записаться, просто напиши /book, и я помогу выбрать подходящее время!

# Сообщения процесса регистрации
registration_start: |
  👋 Привет! Для начала, мне нужен твой номер телефона.

registration_phone_received: |
  🎉 Спасибо! Теперь скажи, как тебя зовут?

registration_age_received: |
  🎂 Супер! Твой возраст {{.Age}} лет учтен. 
  Теперь я знаю о тебе достаточно, чтобы сделать твой опыт с нами максимально комфортным!

registration_complete: |
  🌟 Ура, {{.Name}}! Регистрация завершена успешно. 
  Теперь ты можешь записаться на стрижку или другую услугу у Олеси.
  Используй команду /book, чтобы выбрать удобное время.
  Если нужна помощь, просто напиши /help.

# Сообщения об ошибках
invalid_phone_format: |
  ❌ Неверный формат номера телефона. Пожалуйста, введите номер в формате +7XXXXXXXXXX.

invalid_phone_format_on_server: |
    ❌ Произошла ошибка при проверке номера телефона. Пожалуйста, попробуйте еще раз позже.

phone_already_registered: |
  ⚠️ Этот номер телефона уже зарегистрирован. Пожалуйста, войдите в систему или используйте другой номер.

invalid_name_format: |
  ❌ Пожалуйста, введите корректное имя (только буквы, минимум 2 символа).

general_error: |
  😓 Извините, произошла ошибка. Пожалуйста, попробуйте еще раз позже или свяжитесь с нами напрямую: /contact

registration_error: |
  😕 Ой, что-то пошло не так при регистрации. Не волнуйся, давай попробуем еще раз!
  Используй команду /register, чтобы начать процесс регистрации заново.
  Если проблема повторится, пожалуйста, свяжись с Олесей напрямую: /contact.

already_registered: |
  👋 Привет, {{.Name}}! Ты уже зарегистрирован(а) в системе.
  Ты можешь:
  - Просмотреть свои записи через команду /my_appointments
  - Записаться на новую услугу через /book
  - Изменить запись через /reschedule или отменить её через /cancel.

  Если у тебя возникнут вопросы, используй команду /help.

appointment_success: |
  ✂️ Ура! Ты записан(а) на {{.Date}} в {{.Time}} для {{.Service}} у Олеси.
  📍 Адрес: улица Куйбышева, 79. Жду тебя на твоей новой прическе!

appointment_reschedule: |
  🔄 Твоя запись на {{.OldDate}} была перенесена на {{.NewDate}} в {{.NewTime}}. Увидимся в новом времени!
  Олеся уже готовит инструменты ✂️

appointment_cancel: |
  ❌ Жаль, что тебе пришлось отменить запись на {{.Date}}. Надеюсь, скоро увидимся снова!
  Не забывай, что ты всегда можешь выбрать новое время через команду /book.

after_service_message: |
  🥳 Спасибо, что выбрал(а) Олесю для своей модной стрижки! Надеюсь, ты доволен(а) результатом.
  Если у тебя есть пожелания или вопросы, всегда можешь обратиться.

my_appointments: |
  📋 Твои текущие записи:
  {{ range .Appointments }}
  - {{.Date}} в {{.Time}} для {{.Service}} у Олеси
  {{ else }}
  У тебя пока нет записей. Забронируй время через /book!
  {{ end }}