welcome_message: |
  ✂️ Привет, {{.Username}}! Я - бот барбера Олеси, и моя задача сделать твой визит максимально удобным.
  Я работаю по выходным, и ты всегда можешь найти меня по адресу: улица Куйбышева, 79.
  
  Вот что ты можешь сделать:
  - 🕒 /book - Забронировать время для стрижки или другой услуги
  - 👩‍🎨 /services - Узнать о всех услугах и их стоимости
  - 🤙 /contact - Связаться с Олесей напрямую
  - 💇 /about - Узнать больше об Олесе и ее опыте работы
  - 🔄 /reschedule - Изменить существующую запись
  - ❌ /cancel - Отменить запись
  - 📋 /my_appointments - Посмотреть свои записи

  Если тебе нужно повторно зарегистрироваться, используй команду /register.

  **Важно!** Если ты уже был(а) записан(а) ранее, то можешь просто проверить свои записи или изменить их через команды выше!

unknown_command: |
  ❓ Хмм, кажется, я не знаю такой команды. Попробуй ещё раз или напиши /help, чтобы узнать, что я умею!

services: |
  🛠️ Услуги и цены:
  1. Мужская стрижка – 1100 ₽ (60 минут)
  2. Борода – 700 ₽ (30 минут)
  3. Детская стрижка – 1000 ₽ (60 минут)
  4. Воск – 300 ₽ (15 минут)
  5. Тонировка бороды – 900 ₽ (30 минут)
  6. Тонировка седины – 1000 ₽ (30 минут)

  Выбирай и записывайся через /book!

help: |
  ❓ Нужна помощь? Вот список команд:
  - /register – регистрация нового пользователя
  - /book – запись на услугу
  - /cancel – отмена записи
  - /reschedule – перенос записи
  - /services – услуги и цены
  - /my_appointments – твои записи
  - /contact – связь с Олесей
  - /about - Узнать больше об Олесе и ее опыте работы

contact: |
  📞 Если у тебя возникли вопросы, можешь позвонить по номеру +7 982 467 1365 или написать Олесе в Telegram: t.me/OlesyaHudanina


about_master: |
  👩‍🎨 Знакомься с Олеся! 

  Олеся — профессиональный барбер с опытом более 2 лет. Её стиль — это сочетание классических техник и современных трендов. 

  🌟 **Квалификация**:
  - Сертифицированный мастер по стрижке и укладке волос
  - Специальные курсы по уходу за бородой
  - Постоянное обучение новым техникам

  ✂️ **Услуги, которые предлагает Олеся**:
  - Мужские стрижки
  - Уход за бородой и усами
  - Укладка волос
  - Консультации по выбору стиля

  💬 **Отзывы клиентов**:
  Олеся заботится о своих клиентах и всегда стремится сделать так, чтобы каждый уходил довольным. Вот что говорят о ней:
  
  - "Лучшая стрижка, которую я когда-либо имел!" – Алексей
  - "Олеся знает, как сделать так, чтобы ты чувствовал себя уверенно." – Марина

  🌍 **Где найти Олесю**:
  Она принимает клиентов по адресу: Улица Куйбышева, 79, в уютном салоне, где царит атмосфера уюта и профессионализма.

  📅 Если ты готов записаться, просто напиши /book, и я помогу выбрать подходящее время!


registration_success: |
  🎉 Отличные новости, {{.Name}}! Ты успешно зарегистрирован(а).
  Теперь можно забронировать стрижку или другую услугу у Олеси!
  Используй команду /book, чтобы выбрать подходящее время.

registration_start: |
  👋 Привет! Давай познакомимся поближе. Для начала, скажи, как тебя зовут?

registration_name_received: |
  🎉 Приятно познакомиться, {{.Name}}! Теперь мне нужен твой номер телефона. 
  Это нужно, чтобы Олеся могла связаться с тобой в случае изменений в расписании.
  Напиши его в формате +7XXXXXXXXXX, пожалуйста.

registration_phone_received: |
  📱 Отлично, {{.Name}}! Я записал твой номер {{.Phone}}. 
  Остался последний шаг - напиши свой возраст. Это поможет Олесе лучше подобрать стиль стрижки.

registration_age_received: |
  🎂 Супер! Твой возраст {{.Age}} лет учтен. 
  Теперь я знаю о тебе достаточно, чтобы сделать твой опыт с нами максимально комфортным!

registration_complete: |
  🌟 Ура, {{.Name}}! Регистрация завершена успешно. 
  Теперь ты можешь записаться на стрижку или другую услугу у Олеси.
  Используй команду /book, чтобы выбрать удобное время.
  Если нужна помощь, просто напиши /help.

registration_error: |
  😕 Ой, что-то пошло не так при регистрации. Не волнуйся, давай попробуем еще раз!
  Используй команду /register, чтобы начать процесс регистрации заново.
  Если проблема повторится, пожалуйста, свяжись с Олесей напрямую: /contact.

already_registered: |
  👋 Привет, {{.Name}}! Ты уже зарегистрирован(а) в системе.
  Ты можешь:
  - Просмотреть свои записи через команду /my_appointments
  - Записаться на новую услугу через /book
  - Изменить запись через /reschedule или отменить её через /cancel.

  Если у тебя возникнут вопросы, используй команду /help.

appointment_success: |
  ✂️ Ура! Ты записан(а) на {{.Date}} в {{.Time}} для {{.Service}} у Олеси.
  📍 Адрес: улица Куйбышева, 79. Жду тебя на твоей новой прическе!

appointment_reschedule: |
  🔄 Твоя запись на {{.OldDate}} была перенесена на {{.NewDate}} в {{.NewTime}}. Увидимся в новом времени!
  Олеся уже готовит инструменты ✂️

appointment_cancel: |
  ❌ Жаль, что тебе пришлось отменить запись на {{.Date}}. Надеюсь, скоро увидимся снова!
  Не забывай, что ты всегда можешь выбрать новое время через команду /book.

after_service_message: |
  🥳 Спасибо, что выбрал(а) Олесю для своей модной стрижки! Надеюсь, ты доволен(а) результатом.
  Если у тебя есть пожелания или вопросы, всегда можешь обратиться.

my_appointments: |
  📋 Твои текущие записи:
  {{ range .Appointments }}
  - {{.Date}} в {{.Time}} для {{.Service}} у Олеси
  {{ else }}
  У тебя пока нет записей. Забронируй время через /book!
  {{ end }}